# Generated by Django 2.1.4 on 2019-02-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ava',
            field=models.ImageField(blank='1', upload_to='', verbose_name='аватар'),
        ),
    ]
